name: Test & Build
on: [pull_request]
jobs:
  build:
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 12

      - name: Install dependencies
        run: yarn install --frozen-lockfile

      - name: Build Dist
        run: yarn build

      - name: Bundlewatch
        run: yarn bundlewatch
